version: '3'

services:
  nois-pingpong-testnet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: config/uni-6/config.json
        SECRETS_FILE: config/uni-6/secrets.json
    image: docker.io/noislabs/nois-pingpong:testnet
    ports:
      - "19000:3001"
  nois-pingpong-juno:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: config/juno/config.json
        SECRETS_FILE: config/juno/secrets.json
    image: docker.io/noislabs/nois-pingpong:juno
    ports:
      - "19001:3001"
