version: '3'

services:
  nois-pingpong-testnet:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: config/testnet.json
    image: docker.io/noislabs/nois-pingpong:testnet
    ports:
      - "19000:3001"
  nois-pingpong-juno-public:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_FILE: config/juno-public.json
    image: docker.io/noislabs/nois-pingpong:juno-public
    ports:
      - "19001:3001"
